# Bitcoin price prediction

Examine bitcoin prices and see if we can predict its future price.

In [ ]:
bit_df.tail()

Timestamp      Open      High       Low     Close  Volume_(BTC)  \
1574269  1515369360  16174.21  16174.23  16174.21  16174.23      7.594119   
1574270  1515369420  16174.23  16174.23  16174.21  16174.22     11.902468   
1574271  1515369480  16174.22  16174.22  16174.21  16174.21      3.860840   
1574272  1515369540  16174.22  16174.22  16174.21  16174.22      1.179093   
1574273  1515369600  16174.22  16174.23  16174.22  16174.22      5.401224   

         Volume_(Currency)  Weighted_Price  
1574269      122828.956770    16174.221301  
1574270      192513.150940    16174.221081  
1574271       62446.073684    16174.218136  
1574272       19070.914509    16174.219514  
1574273       87360.593222    16174.220219

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
%%time
# Resampling data from minute interval to day
bit_df = pd.read_csv('gdrive/MyDrive/coinbaseUSD_1-min_data_2014-12-01_to_2018-01-08.csv')
bit_df.head()

FileNotFoundError: ignored

In [ ]:
%%time
# Convert unix time to datetime
bit_df['date'] = pd.to_datetime(bit_df.Timestamp, unit='s')
# Reset index
bit_df = bit_df.set_index('date')
# Rename columns so easier to code
bit_df = bit_df.rename(columns={'Open':'open', 'High': 'hi', 'Low': 'lo',
                       'Close': 'close', 'Volume_(BTC)': 'vol_btc',
                       'Volume_(Currency)': 'vol_cur',
                       'Weighted_Price': 'wp', 'Timestamp': 'ts'})
# Resample and only use recent samples that aren't missing
bit_df = bit_df.resample('d').agg({'open': 'first', 'hi': 'max',
    'lo': 'min', 'close': 'last', 'vol_btc': 'sum',
    'vol_cur': 'sum', 'wp': 'mean', 'ts': 'min'}).iloc[-1000:]
# drop last row as it is not complete
bit_df = bit_df.iloc[:-1]

CPU times: user 104 ms, sys: 32.4 ms, total: 136 ms
Wall time: 159 ms


In [ ]:
bit_df.shape

(999, 8)

In [ ]:
bit_df.head()

open      hi      lo   close      vol_btc       vol_cur  \
date                                                                    
2015-04-15  221.05  224.52  218.09  224.35  9137.584626  2.029524e+06   
2015-04-16  224.35  230.75  223.66  229.45  8636.837666  1.970069e+06   
2015-04-17  229.45  230.08  220.46  223.62  7738.360003  1.741497e+06   
2015-04-18  223.55  224.04  222.18  224.02  5065.649127  1.131269e+06   
2015-04-19  224.02  226.72  223.44  224.03  5279.787312  1.185860e+06   

                    wp            ts  
date                                  
2015-04-15  222.270771  1.429056e+09  
2015-04-16  227.779413  1.429142e+09  
2015-04-17  224.970863  1.429229e+09  
2015-04-18  223.398170  1.429315e+09  
2015-04-19  224.667792  1.429402e+09

In [ ]:
bit_df.tail()

open        hi        lo     close       vol_btc  \
date                                                               
2018-01-03  14781.52  15400.00  14628.00  15098.14  17616.327677   
2018-01-04  15098.23  15400.00  14230.00  15144.99  19567.016783   
2018-01-05  15145.00  17178.00  14819.78  16960.01  22588.046307   
2018-01-06  16960.01  17174.00  16251.01  17098.99  13744.804428   
2018-01-07  17099.00  17115.01  15755.01  16174.22  12201.377159   

                 vol_cur            wp            ts  
date                                                  
2018-01-03  2.642264e+08  14989.939350  1.514938e+09  
2018-01-04  2.909045e+08  14851.477880  1.515024e+09  
2018-01-05  3.619888e+08  15796.596968  1.515110e+09  
2018-01-06  2.296885e+08  16661.988247  1.515197e+09  
2018-01-07  2.002825e+08  16526.973583  1.515283e+09

## Predict tomorrow's close based on today's info
First, predict the open price from the ts component.

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics

In [ ]:
bit_df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 999 entries, 2015-04-15 to 2018-01-07
Freq: D
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   open     999 non-null    float64
 1   hi       999 non-null    float64
 2   lo       999 non-null    float64
 3   close    999 non-null    float64
 4   vol_btc  999 non-null    float64
 5   vol_cur  999 non-null    float64
 6   wp       999 non-null    float64
 7   ts       999 non-null    float64
dtypes: float64(8)
memory usage: 70.2 KB


In [ ]:
bit_df.describe()

open            hi            lo         close        vol_btc  \
count    999.00000    999.000000    999.000000    999.000000     999.000000   
mean    1838.11015   1914.705946   1757.861101   1854.054895   10350.019927   
std     3169.30283   3346.396825   2966.458499   3201.173766    9947.604406   
min      211.16000    224.040000      0.060000    211.160000    1525.187302   
25%      384.61500    393.500000    371.300000    384.850000    5320.152105   
50%      629.79000    639.850000    618.130000    630.830000    7367.614526   
75%     1454.14500   1512.965000   1440.095000   1502.495000   11954.181722   
max    19650.02000  19891.990000  19010.000000  19650.010000  165763.024424   

            vol_cur            wp            ts  
count  9.990000e+02    999.000000  9.990000e+02  
mean   3.553735e+07   1842.224578  1.472170e+09  
std    1.097365e+08   3165.632076  2.492906e+07  
min    7.925465e+05    215.969046  1.429056e+09  
25%    2.297687e+06    384.227045  1.450613e+09  
50%    3.484114e+06    632.673702  1.472170e+09  
75%    1.985804e+07   1471.613323  1.493726e+09  
max    1.393385e+09  19537.276941  1.515283e+09

In [ ]:
bit_df.corr()

open        hi        lo     close   vol_btc   vol_cur        wp  \
open     1.000000  0.997562  0.996579  0.997140  0.526337  0.836192  0.998800   
hi       0.997562  1.000000  0.996036  0.999194  0.540711  0.852631  0.998989   
lo       0.996579  0.996036  1.000000  0.997887  0.503904  0.807838  0.998538   
close    0.997140  0.999194  0.997887  1.000000  0.527407  0.838351  0.999277   
vol_btc  0.526337  0.540711  0.503904  0.527407  1.000000  0.689433  0.525290   
vol_cur  0.836192  0.852631  0.807838  0.838351  0.689433  1.000000  0.833692   
wp       0.998800  0.998989  0.998538  0.999277  0.525290  0.833692  1.000000   
ts       0.650204  0.646562  0.658249  0.650609  0.347119  0.445663  0.652363   

               ts  
open     0.650204  
hi       0.646562  
lo       0.658249  
close    0.650609  
vol_btc  0.347119  
vol_cur  0.445663  
wp       0.652363  
ts       1.000000

In [ ]:
full_x = bit_df[['hi', 'lo', 'close', 'vol_btc', 'vol_cur', 'wp', 'ts']]
full_y = bit_df['open']

In [ ]:
from sklearn.model_selection import train_test_split
full_x_train, full_x_test, full_y_train, full_t_test = train_test_split(full_x, full_y, random_state = 2)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
full_x_train = scaler.fit_transform(full_x_train)
full_x_test = scaler.transform(full_x_test)

In [ ]:
full_x_train.shape

(749, 7)

In [ ]:
x_train = full_x_train[:, 6]
x_test = full_x_test[:, 6]
y_train = full_y_train
y_test = full_t_test

## First part : Predict the open price from the ts component.

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
x_train = x_train.reshape(-1, 1)
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
x_test = x_test.reshape(-1, 1)
predicted = model.predict(x_test)

In [ ]:
from sklearn.metrics import mean_absolute_error as mae

In [ ]:
mae(predicted, y_test)

1419.2864831618238

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, predicted)
r2

0.4123265296257659

In [ ]:
x_test.shape

(250, 1)

In [ ]:
adjusted_r2 = 1 - ((1 - r2)*(x_test.shape[0] - 1)/(x_test.shape[0] - x_test.shape[1] - 1))

In [ ]:
adjusted_r2

0.4099568785355472

## Second Part : Predict tomorrow's close price by today's data

In [ ]:
full_x = bit_df[['open', 'hi', 'lo', 'close', 'vol_btc', 'vol_cur', 'wp', 'ts']]
full_y = bit_df['close']

In [ ]:
full_x.shape

(999, 8)

In [ ]:
full_y.shape

(999,)

### We are trying to predict the close price for the next day based on the previous day's data, so we will take training data according to that

In [ ]:
full_x = full_x.iloc[:998, :]    # we are taking all rows except the last as the feature
full_y = full_y[1:]              # the variable to be predicted is in the immediate next row

In [ ]:
full_x.shape

(998, 8)

In [ ]:
full_y.shape

(998,)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(full_x, full_y, random_state = 2)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)

In [ ]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
predicted = model.predict(X_test)

In [ ]:
mae(predicted, y_test)

85.37116093152662

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, predicted)
r2

0.989147581028806

In [ ]:
X_test.shape

(250, 8)

In [ ]:
adjusted_r2 = 1 - ((1 - r2)*(X_test.shape[0] - 1)/(X_test.shape[0] - X_test.shape[1] - 1))

In [ ]:
adjusted_r2

0.9887873347559033

In [ ]:
bit_df.iloc[-1:]

Timestamp      Open      High       Low     Close  Volume_(BTC)  \
1574273  1515369600  16174.22  16174.23  16174.22  16174.22      5.401224   

         Volume_(Currency)  Weighted_Price  
1574273       87360.593222    16174.220219

## Since the R-squared value is quite good, we can now train the model using all the data that we have in order to make accurate prediction

> Indented block



### To predict what will be tomorrow's closing price we will pass all the values for today (i.e. the last row of bit_df) to the model

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(full_x)
feed = scaler.transform(bit_df.iloc[-2:])

In [ ]:
model = LinearRegression()
model.fit(X_train, full_y)

LinearRegression()

In [ ]:
feed

array([[4.83271523, 4.6124446 , 4.94593735, 4.81534861, 0.34145895,
        1.77275702, 4.73750721, 1.73031615],
       [4.87708932, 4.59463141, 4.77683584, 4.52352037, 0.18630058,
        1.50448508, 4.69438922, 1.7337872 ]])

In [ ]:
y = model.predict(feed)

the actual close price of the last data point is

In [ ]:
full_y[-1]

16174.22

predicted close price for last data point is

In [ ]:
y[-2]

17388.196250754158

#### finally this is the prediction of tomorrow's close price based on today's data i.e the data from the last row

In [ ]:
y[-1]

15999.740639953881

## Save Model

In [ ]:
import pickle
pickle.dump(model, open('models.pkl', "wb"))

In [ ]:
load_model = pickle.load(open('models.pkl', "rb"))
load_model.predict(feed)

array([17388.19625075, 15999.74063995])

In [ ]:
full_x

## This is the predicted tomorrow's close price

In [ ]:
feat = ['Timestamp', 'Open', 'High', 'Low', 'Close', 'Volume_(BTC)', 'Volume_(Currency)', 'Weighted_Price']
ft = ['open', 'hi', 'lo', 'close', 'vol_btc', 'vol_cur', 'wp', 'ts']
input_data = [229.45,	230.08,	220.46,	223.62,	7738.360003,	1.741497e+06,	224.970863,	1.429229e+09]

input_data_nd = np.asarray(input_data)
ty = input_data_nd.reshape(-1, len(input_data))
input_data_df = pd.DataFrame(ty, columns=ft)
input_data_df

open      hi      lo   close      vol_btc    vol_cur          wp  \
0  229.45  230.08  220.46  223.62  7738.360003  1741497.0  224.970863   

             ts  
0  1.429229e+09

In [ ]:
full_x

In [ ]:
# scaler.fit(input_data_df)
fd = scaler.transform(input_data_df)
fd

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
pred_price = load_model.predict(fd)
pred_price[0]

1855.6878657314626